### ISSUE TITLE
impossible to connect

### ISSUE THREAD

**Issue by Grummfy** [freenetdigital/prometheus_oracle_exporter#13]
Hello,
I try https://github.com/iamseth/oracledb_exporter
when I do this call
```
export DATA_SOURCE_NAME=USER/PASSWORD@localhost/DATABASE
./oracledb_exporter
```
I got the information and the database is considered as UP

When i try with this exporter with the configuration file
```
connections:
 - connection: USER/PASSWORD
   database: DATABASE
   instance: DATABASE
   alertlog:
    - file: /oracle/diag/rdbms/....log
      ignoreora:
       - ORA-00001
       - ORA-01033
       - ORA-01041
       - ORA-01089
       - ORA-01555
       - ORA-28
       - ORA-235
       - ORA-609
       - ORA-3136
   queries:
    - sql: "select 1 from dual"
      name: sample1
```
the database is down but I didn't see anything.
