### ISSUE TITLE
breaking in the graph

### ISSUE THREAD

**Issue by Freel-Freel** [freenetdigital/prometheus_oracle_exporter#18]
Thank You for Your work on this Exporter!
I am working with your product and i have a question, if You will be able to help me, i will appreciate it.
On the graph, which i attached, are able to see some breaking in all-over line, i was wonder what kind of problem that symbolises?
Prometheus config:

```
# if alertmanager is not defined on this host, statement will raise error

global:
  evaluation_interval: 20s
  external_labels:
    monitor: test54
  scrape_interval: 1m
  scrape_timeout: 55s
alerting:
  alertmanagers:
    - path_prefix: /alertmanager
      static_configs:
        - targets:
          - test54:19093
rule_files:
- /home/mon/monitoring/conf/prometheus/rules/*.yml
scrape_configs:
- job_name: blackboxes
  metrics_path: "/probe"
  file_sd_configs:
  - files:
    - /home/mon/monitoring/conf/prometheus/files_sd/blackboxes_*.yml
    refresh_interval: 30s
  scrape_interval: 1m
  relabel_configs:
    - source_labels: [__address__]
      regex: "([a-zA-Z0-9]+)://(([A-Za-z0-9.-]+)(?::([0-9]+))?)?(/[a-zA-Z0-9_/-]+)?(?:,([a-zA-Z0-9_]+))?#([a-z0-9-]+):([0-9]+)"
      replacement: '$2$5'
      target_label: __param_target
    - source_labels: [__address__]
      regex: "(https?)://(([A-Za-z0-9.-]+)(?::([0-9]+))?)?(/[a-zA-Z0-9_/-]+)?(?:,([a-zA-Z0-9_]+))?#([a-z0-9-]+):([0-9]+)"
      replacement: '$1://$2$5'
      target_label: __param_target
    - source_labels: [__address__]
      regex: "([a-zA-Z0-9]+)://(([A-Za-z0-9.-]+)(?::([0-9]+))?)?(/[a-zA-Z0-9_/-]+)?(?:,([a-zA-Z0-9_]+))?#([a-z0-9-]+):([0-9]+)"
      replacement: '$1://$2$5'
      target_label: target
    - source_labels: [__address__]
      regex: "([a-zA-Z0-9]+)://(([A-Za-z0-9.-]+)(?::([0-9]+))?)?(/[a-zA-Z0-9_/-]+)?(?:,([a-zA-Z0-9_]+))?#([a-z0-9-]+):([0-9]+)"
      replacement: '$1'
      target_label: __param_module
    - source_labels: ["__address__"]
      regex: "([a-zA-Z0-9]+)://(([A-Za-z0-9.-]+)(?::([0-9]+))?)?(/[a-zA-Z0-9_/-]+)?(?:,([a-zA-Z0-9_]+))?#([a-z0-9-]+):([0-9]+)"
      replacement: '$7'
      target_label: "node"
    - source_labels: [__address__]
      regex: "([a-zA-Z0-9]+)://(([A-Za-z0-9.-]+)(?::([0-9]+))?)?(/[a-zA-Z0-9_/-]+)?(?:,([a-zA-Z0-9_]+))?#([a-z0-9-]+):([0-9]+)"
      replacement: '$6'
      target_label: blackbox_name
    - source_labels: [__address__]
      regex: "([a-zA-Z0-9]+)://(([A-Za-z0-9.-]+)(?::([0-9]+))?)?(/[a-zA-Z0-9_/-]+)?(?:,([a-zA-Z0-9_]+))?#([a-z0-9-]+):([0-9]+)"
      replacement: '$7:$8'
      target_label: __address__
- job_name: automatique
  file_sd_configs:
  - files:
    - /home/mon/monitoring/conf/prometheus/files_sd/auto_*.yml
    refresh_interval: 1m
  scrape_interval: 1m
  relabel_configs:
    - source_labels: ["__address__"]
      target_label:  "__metrics_path__"
      regex: "[A-Za-z0-9-]+:[0-9]+([/a-z]+)(#[a-z0-9]+)?"
    - source_labels: ["__address__"]
      target_label:  "team"
      regex: "[A-Za-z0-9-]+:[0-9]+[/a-z]+(#([a-z0-9]+))?"
      replacement: '$2'
    - source_labels: ["__address__"]
      target_label: "node"
      regex: "([A-Za-z0-9-]+):[0-9]+[/a-z]+(#[a-z0-9]+)?"
    - source_labels: ["__address__"]
      target_label:  "__address__"
      regex: "([A-Za-z0-9-]+:[0-9]+)[/a-z]+(#[a-z0-9]+)?"
  metric_relabel_configs:
    - source_labels: [mountpoint]
      regex: '.+'
      target_label: system
      replacement: 'env'
      action: replace # set default value
    - source_labels: [mountpoint]
      regex: '/home/([a-z]+)_.+'
      target_label: team
      replacement: '$1'
      action: replace
    - source_labels: [mountpoint]
      regex: '/home/ora[a-z0-9]+'
      target_label: system
      replacement: 'oracle'
      action: replace
    - source_labels: [mountpoint]
      regex: '/home/jenkins'
      target_label: system
      replacement: 'jenkins'
      action: replace
    - source_labels: [mountpoint]
      regex: '/home/nexus'
      target_label: system
      replacement: 'nexus'
      action: replace
    - source_labels: [mountpoint]
      regex: '/([a-z0-9_]+)?'
      target_label: system
      replacement: 'infra'
      action: replace
    - source_labels: [mountpoint]
      regex: '/home/([a-z0-9_-]+)'
      target_label: env_name
      replacement: '$1'
      action: replace
```

![image004](https://user-images.githubusercontent.com/18048358/53940606-28e0c700-40c7-11e9-8a9c-29b18fa8b780.png)

![image007](https://user-images.githubusercontent.com/18048358/53940630-326a2f00-40c7-11e9-8482-5444107d4d85.png)
