### ISSUE TITLE
Why exporter had many connections

### ISSUE THREAD

**Issue by Freel-Freel** [freenetdigital/prometheus_oracle_exporter#21]
Thank You for Your work on this Exporter!
I am working with your product and i have a question, if You will be able to help me, i will appreciate it. 
I connected to the ORACLE and saw:
```
SQL > select username, count(*) from v$sessions group by username;
USENAME                   COUNT(*)
--------------------------------
USER1                                2
MONITORING                    126
SYS                                     1
```

We use MONITORING (ORACLE user) for oracle_exporter and it's hold 126 sessions. It is all-time-long fact. Why is this happening?

![telegram-cloud-file-2-257901626-255282--373329220835460863](https://user-images.githubusercontent.com/18048358/56387031-f2e94380-622b-11e9-9d4f-d8312ce2bf13.jpg)

**Comment by Freel-Freel** [comment]
Config exporter:
```
---
connections:
  - connection: MONITORING/ORACLE_EXPORTER@DEV13
    database: DEV13
    instance: DEV13
    alertlog:
      - file: /home/oracle/app/oracle/oradata/dev13/diag/rdbms/dev13/dev13/trace/alert_dev13.log
        ignoreora:
          - ORA-00001
          - ORA-01033
          - ORA-01041
          - ORA-01089
          - ORA-01555
          - ORA-28
          - ORA-235
          - ORA-609
          - ORA-3136
    queries:
    - name: LongSession
      sql: SELECT count(*) FROM ( SELECT sid, serial#, ROUND(((l.cpu_time) / 1000000 / 60), 1) as CPU_TIME_minute, ROUND(((l.elapsed_time) / 1000000 / 60), 1) as ELAPSED_TIME_minute, ls.username FROM     v$sql l, v$session ls WHERE ls.sql_address = l.address) WHERE CPU_TIME_minute > 0.1 AND USERNAME IS NOT NULL
    - name: CountSessionMonitoring
      sql: SELECT COUNT(*) FROM v$session WHERE USERNAME = 'MONITORING'
    - name: sample1
      sql: select 1 from dual
```
