### ISSUE TITLE
No more than two instances supported for scraping metrics

### ISSUE THREAD

**Issue by azet** [freenetdigital/prometheus_oracle_exporter#24]
Hi,

Apparently the way this exporter is written its not possible to enumerate more than two databases/instances. While it enumerates all possible alertlog files it doesn't do DB queries to scrape for interconnect, tablespace, service, sysstat, or waitclass.

Example of a live configuration with 8 instances, 7 of them active:

```
...
lots of metrics before with only two instances from the config file reflected in them
...

oracledb_up{database="DEDI1",dbinstance="DEDI1"} 1
oracledb_up{database="PARCH1",dbinstance="PARCH1"} 1
oracledb_up{database="PCOOP1",dbinstance="PCOOP1"} 1
oracledb_up{database="PEXITE1",dbinstance="PEXITE1"} 1
oracledb_up{database="PGEN1",dbinstance="PGEN1"} 0
oracledb_up{database="PINT1",dbinstance="PINT1"} 1
oracledb_up{database="PSTERI1",dbinstance="PSTERI1"} 1
oracledb_up{database="TEDI1",dbinstance="TEDI1"} 1
# HELP oracledb_uptime Gauge metric with uptime in days of the Instance.
# TYPE oracledb_uptime gauge
oracledb_uptime{database="PEXITE1",dbinstance="PEXITE12"} 30.667696759259258
oracledb_uptime{database="TEDI1",dbinstance="TEDI11"} 30.67241898148148
# HELP oracledb_waitclass Gauge metric with Waitevents (v$waitclassmetric).
# TYPE oracledb_waitclass gauge
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="administrative"} 0
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="application"} 0
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="cluster"} 0.012
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="commit"} 0.033
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="concurrency"} 0.001
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="configuration"} 0
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="network"} 0
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="other"} 0.015
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="scheduler"} 0
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="system_io"} 0.034
oracledb_waitclass{database="PEXITE1",dbinstance="PEXITE12",type="user_io"} 0.003
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="administrative"} 0
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="application"} 0
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="cluster"} 0
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="commit"} 0.001
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="concurrency"} 0
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="configuration"} 0
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="network"} 0
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="other"} 0.011
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="scheduler"} 0
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="system_io"} 0.015
oracledb_waitclass{database="TEDI1",dbinstance="TEDI11",type="user_io"} 0.005
```

I think the reason is that the scrape functions just do a simple `.Next()` and don't iterate over all entries that the config file offers.

**Comment by floyd871** [comment]
There is no limitation of instances, but prometheus has a scrape timeout. 
Did you manual do a "curl" on the exporter endpoint and looked at the output?
Can you please provide your configuration.

**Comment by azet** [comment]
Hi,

The config has this layout (redacted because its a productive system):

```
connections:
 - connection: user/pwd@instance/SERVICE
   database: xxx
   instance: xxx
   alertlog:
    - file: oracle.conf
#   queries:
#    - sql: "select 1 from dual"
#      name: sample1
#    - sql: "select 2 from dual"
#      name: sample2

 - connection: user/pwd@instance/SERVICE
   database: xzx
   instance: xzx
   alertlog:
    - file: oracle.conf
#   queries:
#    - sql: "select 1 from dual"
#      name: sample1
#    - sql: "select 2 from dual"
#      name: sample2

 - connection: user/pwd@instance/SERVICE
   database: xzy
   instance: xzy
   alertlog:
    - file: oracle.conf
#   queries:
#    - sql: "select 1 from dual"
#      name: sample1
#    - sql: "select 2 from dual"
#      name: sample2

...
```

I include oracle conf as alert log because I dont have the alertlogs on this host (for how) and the exporter fails if this is missing in the YAML.

Even though there are 8 different host/service entries in my config file only the first two are used for scraping. I added some debug lines during SQL connection establishment and I can see that the exporter connects to all 8 (one of which is down so successfully connects to 7). But only "xxx" and "xyx" in this example are exported.

I did a curl above in the original report.
