### ISSUE TITLE
Initial query failed

### ISSUE THREAD

**Issue by Freel-Freel** [freenetdigital/prometheus_oracle_exporter#7]
Thank You for Your work on this Exporter!
I am working with your product and i have a problem with it, if You will be able to help me, i will appreciate it. 

The problem is: when Exporter connecting with ORACLE, i got the following error:

`time="2018-10-05T11:51:26+03:00" level=info msg="Connect OK, Inital query failed:  exporter_test/exporter_test@TEST09" source="main.go:789"
`

The connection way was: created file $ vim ~/tnsnames.ora

```
TEST09=                                                                                                                                                                     
(DESCRIPTION=                                                                                                                                                               
  (ADDRESS=(PROTOCOL=TCP)(HOST=192.168.1.200)(PORT=1521)                                                                                                                           
  )                                                                                                                                                                         
  (CONNECT_DATA=                                                                                                                                                            
    (SID=test09)                                                                                                                                                            
  )                                                                                                                                                                         
) 
```

Exporter config:

```
connections:
  - connection: exporter_test/exporter_test@TEST09
    database: TEST09
    instance: TEST09
    alertlog:
      - file: /data/oracle/diag/rdbms/develop/DEVELOP/trace/alert_DEVELOP.log
        ignoreora:
          - ORA-00001
          - ORA-01033
          - ORA-01041
          - ORA-01089
          - ORA-01555
          - ORA-28
          - ORA-235
          - ORA-609
          - ORA-3136
    queries:
     - sql: "select 1 from dual"
       name: sample1
     - sql: "select 2 from dual"
       name: sample2​
```

Hope to hear from You soon!
Best Regards
