### ISSUE TITLE
Timeout needed on connection level

### ISSUE THREAD

**Issue by This-is-me-now** [freenetdigital/prometheus_oracle_exporter#73]
Hi!

We are running the exporter separated from the target machines in a Kubernetes pod. Reason is, that we are not allowed to install the needed version of instant client on the target hosts.

Currently we have four hosts monitored by one pod which normally runs smoothly.

But somtimes one or more hosts need to long to answer, which makes the scrape running in the timeout set by Prometheus:

`Get http://11.22.33.44:9161/metrics: context deadline exceeded`

In that case, no information is collected at all, even not from the connections answering within the limits. Is there a possibility to set a timeout for each connection so that if one ore more hosts are to busy (or even down?), we can at least get metrics from the other ones?

Config example of how I would imagine it:

```
Connections:
 - connection: system/oracle@10.0.2.15
   database: DEVELOP
   instance: DEVELOP
   timeout: 5s
   [...]

 - connection: <user>/<pass>@<tnsname>
   database: STAGE
   instance: STAGE
   timeout: 5s
   [...]
```

Thanks and best regards
