### ISSUE TITLE
Limiting the scrape scope per database or instance

### ISSUE THREAD

**Issue by ulikl** [freenetdigital/prometheus_oracle_exporter#74]
Hi Michael,

I find you exporter really awesome, especially the possibility to configure multiple databases.
I would like to have only very few instance on central servers, scraping a lot of databases.
But I have concerns that the scraping of all of these databases at once will take too long.
Using a separate exporter instance per database would need a lot of separate ports on the central servers.

It would be awesome, if the exporter could be extended -- analog to blackbox exporter(https://github.com/prometheus/blackbox_exporter) or exporter_exporter (https://github.com/QubitProducts/exporter_exporter) -- so that I can supply the database/instance  to scrape as parameter.
The Prometheus scrape job could look like
```
- job_name: 'oracle-single-db'
    scrape_interval: 1m
    scrape_timeout: 55s
    metrics_path: /metrics
    params:
      instance: inst1
      database: db1
     ...
```
Only the metrics for databases matching the instance and/or database labels in the config file, should be queried and their metrics returned.

I'm looking forward to your opinion.

Kind Regards,
 Ulrike
