### ISSUE TITLE
custom scrape interval 

### ISSUE THREAD

**Issue by isshwar** [freenetdigital/prometheus_oracle_exporter#75]
Hi,

Going through the readme, i could not find the scrape interval for the exporter. What is the default scrape interval of the exporter to the database. 

Also, if there is a default interval can this be overridden?. I have some custom metrics and i want them to be scrapped only once in a day. 

Thanks
Eswar

**Comment by AaronDewes** [comment]
HI!

This example from the README shows that you can set `scrape_interval`, or have you solved your issue?

```
scrape_configs:
  - job_name: 'oracle-short'
    metrics_path: /metrics
    static_configs:
      - targets:
        - oracle.host.com:9161
    relabel_configs:
     - source_labels: ['__address__']
       target_label: instance
       regex:  '(.*):\d+'
       replacement: "${1}"

  - job_name: 'oracle-tab'
    scrape_interval: 6h
    scrape_timeout: 120s
    metrics_path: /metrics
    params:
      tablerows: [true]
      lobbytes: [true]
      recovery: [true]
    static_configs:
      - targets:
         - oracle.host.com:9161
    relabel_configs:
     - source_labels: ['__address__']
       target_label: instance
       regex:  '(.*):\d+'
       replacement: "${1}"

  - job_name: 'oracle-ind'
    scrape_interval: 6h
    scrape_timeout: 120s
    metrics_path: /metrics
    params:
      tablebytes: [true]
      indexbytes: [true]
      recovery: [true]
    static_configs:
      - targets:
         - oracle.host.com:9161
    relabel_configs:
     - source_labels: ['__address__']
       target_label: instance
       regex:  '(.*):\d+'
       replacement: "${1}"
```
