### ISSUE TITLE
Database name in configuration has no effect other than labeling the scrape output

### ISSUE THREAD

**Issue by This-is-me-now** [freenetdigital/prometheus_oracle_exporter#81]
We have to monitor several schemas on one host, so we made a config like this:

```
connections:
 - connection: myuser/mypass@myserver:1850/SOMEID
   database: db1
   instance: db1
 - connection: myuser/mypass@myserver:1850/SOMEID
   database: db2
   instance: db2
 - connection: myuser/mypass@myserver:1850/SOMEID
   database: db3
   instance: db3
[...]
```
The scrape returns tablemetrics for every schema separately, but they are all identical, propably the default schema based on the connection string. It seems to me that "database" is just a value given back in the scrape and does not trigger a "use [schemaname]" in the scrape process. Even if I enter a nonexisting schema there, I get the same result. Is that intended?
